---
#
# Task to release EC2 instance
#
# Arguments:
# instance_name = <any character>

- name: Get EC2 instance details
  ec2_instance_facts:
    filters:
      "tag:Name": "{{instance_name}}"
  register: ec2_instance_details
  when:
    - ec2_operation is defined
    - ec2_operation == "release_instance"
  delegate_to: localhost
  tags:
    - ec2_operations

- name: Deprovision EC2 instance
  ec2:
    state: absent
    instance_ids: "{{ec2_instance_details.instances[0].instance_id}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key}}"
  delegate_to: localhost
  tags:
    - ec2_operations

